version: "3"
services:
  respiratory-sound:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_for_cpu
    container_name: "respiratory-sound"
    tty: true
    privileged: true
    volumes:
      - ./notebooks:/tf/notebooks
      - ./dataset:/tf/dataset
    command: jupyter-lab --allow-root --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --notebook-dir=/tf
    ports:
      - "8888:8888"
